/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32l4xx.h"

#define PIN_5				(1U<<5)
#define LED_PIN				PIN_5

#define PIN_13				(1U<<13)
#define BTN_PIN				PIN_13

#define GPIOAEN				(1U<<0)
#define GPIOCEN				(1U<<2)

int main(void)
{
	/* enable clock access to GPIOA */
	RCC->AHB2ENR |= GPIOAEN;
	/* enable clock access to GPIOC */
	RCC->AHB2ENR |= GPIOCEN;

	/* set PA5 as output pin */
	GPIOA->MODER |= (1U<<10); // set bit 10 to 1
	GPIOA->MODER &= ~(1U<<11); // set bit 11 to 0

	/* set PC13 as input pin */
	GPIOC->MODER &= ~(1U<<26);
	GPIOC->MODER &= ~(1U<<27);

	while(1)
	{
		/* check if button is pressed */
		if (GPIOC->IDR & BTN_PIN)
		{
			/* turn on the LED */
			GPIOA->BSRR |= (1U<<5);
		}
		else
		{
			/* turn off the LED */
			GPIOA->BSRR |= (1U<<21);
		}
	}
}
