/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32l4xx.h"
#include "adc.h"
#include "uart.h"
#include "systick.h"
#include "tim.h"
#include "exti.h"

#define PIN_5				(1U<<5)
#define LED_PIN				PIN_5

#define GPIOAEN				(1U<<0)

#define AF1_TIM				(1U<<20)

int main(void)
{
	/* 1. enable clock access to GPIOA */
	RCC->AHB2ENR |= GPIOAEN;

	/* 2. set PA5 as output pin */
	GPIOA->MODER |= (1U<<10);
	GPIOA->MODER &= ~(1U<<11);

	pc13_exti_init();
	uart2_tx_init(USART2);

	while(1)
	{

	}
}

void EXTI15_10_IRQHandler(void)
{
	if ((EXTI->PR1 & PIN13) != 0)
	{
		/* clear PR flag */
		EXTI->PR1 |= PIN13;

		/* toggle */
		GPIOA->ODR ^= LED_PIN;

		printf("BTN pressed...\n\r");
	}
}




