/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 *
 * STM32L476xx
 *
 */

#include <stdint.h>
#include "stm32l4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define ever	;;

void dma2_chan7_usart1(void);

char buffer[120] = {'\0'};

int main(void)
{
	dma2_chan7_usart1();

    /* Loop forever */
	for(ever);
}

void dma2_chan7_usart1(void)
{
	RCC->AHB1ENR |= RCC_AHB1ENR_DMA2EN;
	DMA2_Channel7->CCR &= ~DMA_CCR_EN;
	DMA2_Channel7->CCR &= ~DMA_CCR_PSIZE;
	DMA2_Channel7->CCR &= ~DMA_CCR_MSIZE;
	DMA2_Channel7->CCR &= ~DMA_CCR_PINC;
	DMA2_Channel7->CCR |= DMA_CCR_MINC;
	DMA2_Channel7->CCR &= ~DMA_CCR_DIR;
	DMA2_Channel7->CNDTR = 6;
	DMA2_Channel7->CPAR = (uint32_t)&(USART1->RDR);
	DMA2_Channel7->CMAR = (uint32_t)buffer;
	DMA2_CSELR->CSELR &= ~DMA_CSELR_C6S;
	DMA2_CSELR->CSELR |= 2<<24;
	DMA2_Channel7->CCR |= DMA_CCR_EN | DMA_CCR_TCIE;

	DMA2_Channel7->CCR &= ~DMA_CCR_HTIE;

	NVIC_SetPriority(DMA2_Channel7_IRQn, 0);
	NVIC_EnableIRQ(DMA2_Channel7_IRQn);
}

void DMA2_CH7_IRQHandler(void)
{
	if ((DMA2->ISR & DMA_ISR_TCIF7) == DMA_ISR_TCIF7)
	{
		DMA2->IFCR |= DMA_IFCR_CTCIF7;
	}

	if ((DMA2->ISR & DMA_ISR_HTIF7) == DMA_ISR_HTIF7)
	{
		DMA2->IFCR |= DMA_IFCR_CHTIF7;
	}

	if ((DMA2->ISR & DMA_ISR_GIF7) == DMA_ISR_GIF7)
	{
		DMA2->IFCR |= DMA_IFCR_CGIF7;
	}

	if ((DMA2->ISR & DMA_ISR_TEIF7) == DMA_ISR_TEIF7)
	{
		DMA2->IFCR |= DMA_IFCR_CTEIF7;
	}
}

