/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// where is the led connected ?
// port: A = AHB2
// pin: 5

#include <stdint.h>

#define PERIPH_BASE 		(0x40000000UL)
#define AHB2_OFFSET 		(0x08000000UL)
#define AHB1_OFFSET 		(0x00020000UL)

#define AHB2_PERIPH_BASE  	(PERIPH_BASE + AHB2_OFFSET)
#define AHB1_PERIPH_BASE  	(PERIPH_BASE + AHB1_OFFSET)

#define RCC_OFFSET			(0x00001000UL)
#define RCC_BASE			(AHB1_PERIPH_BASE + RCC_OFFSET)

#define GPIOA_OFFSET		(0x000UL)
#define GPIOA_BASE			(AHB2_PERIPH_BASE + GPIOA_OFFSET)

#define PIN_5				(1U<<5)
#define LED_PIN				PIN_5

#define GPIOAEN				(1U<<0)


typedef struct
{
	volatile uint32_t MODER;
	volatile uint32_t DUMMY[4];
	volatile uint32_t ODR;
} GPIO_TypeDef;

typedef struct
{
	volatile uint32_t DUMMY[19];
	volatile uint32_t AHB2ENR;
} RCC_TypeDef;

#define GPIOA				((GPIO_TypeDef *)GPIOA_BASE)
#define RCC					((RCC_TypeDef *)RCC_BASE)

int main(void)
{
	/* 1. enable clock access to GPIOA */
	RCC->AHB2ENR |= GPIOAEN;

	/* 2. set PA5 as output pin */
	GPIOA->MODER |= (1U<<10); // set bit 10 to 1
	GPIOA->MODER &= ~(1U<<11); // set bit 11 to 0

	while(1)
	{
		/* 3. set PA5 high */

		/* 4. experiment: led toggle */
		GPIOA->ODR ^= LED_PIN;
		for (int i = 0; i < 100000; i++){}
	}
}













