/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32l4xx.h"
#include "adc.h"
#include "uart.h"

void pseudo_delay(void);

uint32_t sensor_value;

int main(void)
{
	pa4_adc1_init();

	pseudo_delay();

	start_conversion();

	uart2_tx_init(USART2);

	while(1)
	{
		sensor_value = adc_read();

		printf("sensor value: %d\n\r", (int)sensor_value);
	}
}

void pseudo_delay(void)
{
	int x;
	for (int i = 0; i < 8000; i++)
	{
		x++;
	}
}




